services:
  wordpress:
    image: wordpress:6.8.2-php8.3-fpm
    container_name: wordpress_app
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - ./app/public:/var/www/html   # map source code WordPress

  webserver:
    image: nginx:alpine
    container_name: wordpress_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./app/public:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress

  db:
    image: mysql:8.0
    container_name: wordpress_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress_db
    ports:
      - "3308:3306"
    volumes:
      - ./db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: wordpress_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_UPLOAD_LIMIT: 256M
    ports:
      - "8081:80"

volumes:
  db-data: